name: Build and Test default scheme

on: 

  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app && /usr/bin/xcodebuild -version
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace SwiftTemplate.xcworkspace -scheme SwiftTemplate -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Test
      run: xcodebuild -workspace SwiftTemplate.xcworkspace -scheme SwiftTemplate -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1